#!/usr/bin/env bun

/**
 * Generates the app-manifest.ts file by scanning packages/app/dist/
 * This creates import statements for all frontend assets using Bun's
 * `with { type: "file" }` syntax for embedding into the binary.
 */

import path from "path"
import fs from "fs"
import { fileURLToPath } from "url"

const __filename = fileURLToPath(import.meta.url)
const __dirname = path.dirname(__filename)

const appDistDir = path.resolve(__dirname, "../../app/dist")
const outputFile = path.resolve(__dirname, "../src/server/app-manifest.ts")

// MIME type mappings
const mimeTypes: Record<string, string> = {
  ".html": "text/html; charset=utf-8",
  ".js": "application/javascript; charset=utf-8",
  ".css": "text/css; charset=utf-8",
  ".json": "application/json; charset=utf-8",
  ".woff2": "font/woff2",
  ".woff": "font/woff",
  ".ttf": "font/ttf",
  ".svg": "image/svg+xml",
  ".png": "image/png",
  ".ico": "image/x-icon",
  ".aac": "audio/aac",
  ".webmanifest": "application/manifest+json",
  ".map": "application/json",
}

function getMimeType(filePath: string): string {
  const ext = path.extname(filePath).toLowerCase()
  return mimeTypes[ext] || "application/octet-stream"
}

function sanitizeVarName(filePath: string): string {
  // Convert file path to a valid JS variable name
  // e.g., "assets/index-BCXcO0Zi.js" -> "assets_index_BCXcO0Zi_js"
  return filePath
    .replace(/[^a-zA-Z0-9]/g, "_")
    .replace(/^_+/, "")
    .replace(/_+$/, "")
    .replace(/_+/g, "_")
}

function getAllFiles(dir: string, baseDir: string = dir): string[] {
  const files: string[] = []
  const entries = fs.readdirSync(dir, { withFileTypes: true })

  for (const entry of entries) {
    const fullPath = path.join(dir, entry.name)
    if (entry.isDirectory()) {
      files.push(...getAllFiles(fullPath, baseDir))
    } else {
      // Get relative path from base dir
      const relativePath = path.relative(baseDir, fullPath)
      files.push(relativePath)
    }
  }

  return files
}

async function generate() {
  if (!fs.existsSync(appDistDir)) {
    console.error(`Error: ${appDistDir} does not exist. Run 'bun run build' in packages/app first.`)
    process.exit(1)
  }

  const files = getAllFiles(appDistDir)
  console.log(`Found ${files.length} files in ${appDistDir}`)

  const imports: string[] = []
  const assetEntries: string[] = []

  for (const file of files) {
    // Skip source maps in production
    if (file.endsWith(".map")) continue
    // Skip _headers file (Cloudflare-specific)
    if (file === "_headers") continue

    const varName = `asset_${sanitizeVarName(file)}`
    const urlPath = "/" + file.replace(/\\/g, "/")
    const mimeType = getMimeType(file)

    // Use relative path from the output file location to app/dist
    const relativePath = "../../../app/dist/" + file.replace(/\\/g, "/")

    imports.push(`import ${varName} from "${relativePath}" with { type: "file" }`)
    assetEntries.push(`  ["${urlPath}", { path: ${varName}, mime: "${mimeType}" }]`)
  }

  // Add root path mapping to index.html
  const indexEntry = assetEntries.find((e) => e.includes('"/index.html"'))
  if (indexEntry) {
    // Extract the asset reference from the index.html entry
    assetEntries.unshift(`  ["/", { path: asset_index_html, mime: "text/html; charset=utf-8" }]`)
  }

  const content = `// This file is auto-generated by generate-app-manifest.ts
// Do not edit manually
// @ts-nocheck - Bun's file embedding imports are not understood by TypeScript

${imports.join("\n")}

export interface Asset {
  path: string
  mime: string
}

export const assets = new Map<string, Asset>([
${assetEntries.join(",\n")}
])

// Index HTML path for SPA fallback
export const indexHtmlPath = asset_index_html
`

  fs.writeFileSync(outputFile, content)
  console.log(`Generated ${outputFile} with ${files.length} assets`)
}

generate().catch((err) => {
  console.error("Failed to generate app manifest:", err)
  process.exit(1)
})
